name: Cimon Sample Report Detect

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}

      - uses: actions/checkout@v3
      
      - name: Simple Connection
        run: curl https://cycode.com
