name: Cimon Sample Report Detect on PR

on: pull_request

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
          report-process-tree: true
          report-pr-summary: true

      - uses: actions/checkout@v4
      
      - name: Connect to Cycode
        run: curl https://app.cycode.com/account/login --http1.1

      - name: Connect to Google
        run: curl google.com --http1.1
