name: Cimon Sample Report Detect

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
          report-process-tree: true

      - uses: actions/checkout@v3
      
      - name: Connect to Cycode
        run: curl https://app.cycode.com/account/login --http1.1

      - name: Connect to Google
        run: curl google.com --http1.1
